# Generated by Django 5.1.1 on 2024-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_assignment_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
