# Generated by Django 5.1.1 on 2024-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_assignment_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submitted_response',
            field=models.TextField(default='Please Post your response right here!'),
        ),
    ]
