# Generated by Django 5.1.1 on 2024-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_assignment_submission_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_submit_button_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
