# Generated by Django 5.1.1 on 2024-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_assignment_is_submit_button_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='No title', max_length=100),
        ),
    ]
