# Generated by Django 5.1.1 on 2024-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='course_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
